ALTER TABLE follows
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE follows
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE follows
    DROP CONSTRAINT pk_follows;

ALTER TABLE follows
    ADD CONSTRAINT pk_follows PRIMARY KEY (id);

DROP INDEX idx_follows_following_follower;

CREATE UNIQUE INDEX uk_follows_active_relation
    ON follows (follower_id, following_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_follows_active_following
    ON follows (following_id, follower_id)
    WHERE deleted_at IS NULL;
