CREATE TABLE posts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id      BIGINT                   NOT NULL,
    content        VARCHAR(500)             NOT NULL,
    parent_post_id BIGINT,
    quoted_post_id BIGINT,
    repost_of_id   BIGINT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_posts_parent FOREIGN KEY (parent_post_id) REFERENCES posts (id) ON DELETE SET NULL,
    CONSTRAINT fk_posts_quoted FOREIGN KEY (quoted_post_id) REFERENCES posts (id) ON DELETE SET NULL,
    CONSTRAINT fk_posts_repost_of FOREIGN KEY (repost_of_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT ck_posts_single_reference CHECK (
        (parent_post_id IS NOT NULL)::int + (quoted_post_id IS NOT NULL)::int + (repost_of_id IS NOT NULL)::int <= 1
    ),
    CONSTRAINT ck_posts_repost_has_no_content CHECK ((repost_of_id IS NULL) = (content <> ''))
);

CREATE INDEX idx_posts_author ON posts (author_id);
CREATE INDEX idx_posts_active_parent ON posts (parent_post_id) WHERE deleted_at IS NULL AND parent_post_id IS NOT NULL;
CREATE INDEX idx_posts_active_quoted ON posts (quoted_post_id) WHERE deleted_at IS NULL AND quoted_post_id IS NOT NULL;
CREATE INDEX idx_posts_active_repost_of ON posts (repost_of_id) WHERE deleted_at IS NULL AND repost_of_id IS NOT NULL;
CREATE UNIQUE INDEX uk_posts_active_repost
    ON posts (author_id, repost_of_id) WHERE deleted_at IS NULL AND repost_of_id IS NOT NULL;

CREATE TABLE post_counts
(
    post_id      BIGINT NOT NULL,
    reply_count  BIGINT NOT NULL DEFAULT 0,
    quote_count  BIGINT NOT NULL DEFAULT 0,
    repost_count BIGINT NOT NULL DEFAULT 0,
    like_count   BIGINT NOT NULL DEFAULT 0,
    view_count   BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_post_counts PRIMARY KEY (post_id),
    CONSTRAINT fk_post_counts_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT ck_post_counts_non_negative CHECK (
        reply_count >= 0 AND quote_count >= 0 AND repost_count >= 0 AND like_count >= 0 AND view_count >= 0
        )
);

CREATE TABLE post_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT                   NOT NULL,
    post_id    BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_post_likes PRIMARY KEY (id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_post_likes_active_relation
    ON post_likes (user_id, post_id) WHERE deleted_at IS NULL;

CREATE INDEX idx_post_likes_active_post
    ON post_likes (post_id, user_id) WHERE deleted_at IS NULL;

CREATE TABLE post_views
(
    post_id   BIGINT                   NOT NULL,
    user_id   BIGINT                   NOT NULL,
    viewed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_post_views PRIMARY KEY (post_id, user_id),
    CONSTRAINT fk_post_views_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_views_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
