-- 미디어(이미지) 객체의 메타데이터. 바이트는 S3 에 있고 storage_key 가 객체 키다.
-- PENDING = presigned PUT 발급됨(객체 유무 미확인) · READY = 완료 API 가 S3 HEAD·내용 검증을 마침.
-- post_id 는 게시글에 첨부된 뒤에만 채워지고(작성 트랜잭션에서 한 번), 첨부는 되돌리지 않는다.
CREATE TABLE media
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id     BIGINT                   NOT NULL,
    post_id      BIGINT,
    position     INTEGER,
    status       VARCHAR(16)              NOT NULL,
    storage_key  VARCHAR(255)             NOT NULL,
    content_type VARCHAR(64)              NOT NULL,
    size_bytes   BIGINT                   NOT NULL,
    width        INTEGER,
    height       INTEGER,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    ready_at     TIMESTAMP WITH TIME ZONE,
    deleted_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_media PRIMARY KEY (id),
    CONSTRAINT fk_media_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_media_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT ck_media_status CHECK (status IN ('PENDING', 'READY')),
    CONSTRAINT ck_media_attachment CHECK ((post_id IS NULL) = (position IS NULL)),
    CONSTRAINT ck_media_size_positive CHECK (size_bytes > 0),
    CONSTRAINT ck_media_ready_has_ready_at CHECK ((status = 'READY') = (ready_at IS NOT NULL))
);

CREATE UNIQUE INDEX uk_media_storage_key ON media (storage_key);
-- 같은 게시글 안에서 위치가 겹치지 않는다. 첨부 UPDATE 가 position 을 0..n-1 로 한 트랜잭션에서 채운다.
CREATE UNIQUE INDEX uk_media_post_position ON media (post_id, position) WHERE post_id IS NOT NULL;
CREATE INDEX idx_media_owner ON media (owner_id);
